# Generated by Django 3.2.8 on 2021-11-18 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nazwa roweru')),
                ('desc', models.CharField(max_length=500, verbose_name='Opis roweru')),
                ('cost', models.FloatField(verbose_name='Cena za godzinę')),
                ('type', models.CharField(choices=[('Crossowy', 'T1'), ('Trekkingowy', 'T2'), ('Miejski', 'T3'), ('MTB', 'T4'), ('Młodzieżowy', 'T5'), ('Dla dzieci', 'T6'), ('BMX', 'T7')], default='Crossowy', max_length=11, verbose_name='Typ roweru')),
            ],
            options={
                'verbose_name': 'Rower',
                'verbose_name_plural': 'Rowery',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Czas od')),
                ('end_time', models.DateTimeField(verbose_name='Czas do')),
                ('num_hours', models.IntegerField(verbose_name='Liczba godzin')),
                ('total_cost', models.FloatField(verbose_name='Łączny koszt')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_cient', to=settings.AUTH_USER_MODEL, verbose_name='Klient')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_item', to='main.bicycle', verbose_name='Rower')),
            ],
            options={
                'verbose_name': 'Wypożyczenie',
                'verbose_name_plural': 'Wypożyczenia',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='treść zgłoszenia')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_client', to=settings.AUTH_USER_MODEL, verbose_name='Klient')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_item', to='main.bicycle', verbose_name='Rower')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_rental', to='main.rental', verbose_name='Wypożyczenie')),
            ],
            options={
                'verbose_name': 'Zgłoszenie',
                'verbose_name_plural': 'Zgłoszenia',
            },
        ),
    ]
