# Generated by Django 3.2.8 on 2022-01-25 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='data zgłoszenia'),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='type',
            field=models.CharField(choices=[('Górski', 'Górski'), ('Szosowy', 'Szosowy'), ('Turystyczny', 'Turystyczny'), ('Inny', 'Inny')], default='Górski', max_length=11, verbose_name='Typ roweru'),
        ),
    ]
