# Generated by Django 3.2.8 on 2022-01-27 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_rental_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_item', to='main.bicycleitem', verbose_name='Rower'),
        ),
    ]
